apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80        # Exposing port 80 for HTTP (you can later change it for HTTPS)
      targetPort: 4499 # Port on which the app is running
  type: LoadBalancer   # Makes the service accessible externally
